### PR TITLE
added loading states

### PR DESCRIPTION
**Pull request by pgdureza**
generic loading dots
chrome-capture-2023-0-19

button loading states
image

### CODE REVIEW

**Comment by rjvillanueva89** [comment]
smoot smoot

**Review by jubalm — COMMENTED** [review]
I feel inclined to think that the button with loading state should also be disabled?

**Comment by rjvillanueva89** [comment]
> I feel inclined to think that the button with loading state should also be disabled?
> 
> Is this usable for #4 @rjvillanueva89 ?

yes please! I got a lot of "nothing is happening" feedback and also just to disable a re-submits.

**Review by rjvillanueva89 — COMMENTED** [review]
I've checked it out and I'm good with everything

**Review by rjvillanueva89 — APPROVED** [review]
I've checked it out and I'm good with everything #4 closed

**Pull request merged**
