### PR TITLE
added hero icons

### PR DESCRIPTION
**Pull request by pgdureza**

### CODE REVIEW

**Review by jubalm — COMMENTED** [review]
I can't seem to find in this PR if hero icons are being used yet? or does this fix some dependency issue prior?

**Comment by pgdureza** [comment]
yes, this isn't using the actual library yet. this is just to add the module so we can have icons. We used the same library before in our other project, but manually copied the SVGs. I figured instead of having to manage the SVGs in our code base, we can just install the library now. Can leave the PR open for now until we need an icon to be used.

**Comment by rjvillanueva89** [comment]
I can manually create this if you guys want (or figure out how to scrape the svg codes); [ui/Icons.tsx](https://github.com/UpBrewTech/project-leasa/blob/e291784ab4c1c8a6005ff7c57d59bb54f090c24c/packages/ui/Icons.tsx)

(I'm nott sure how often they release new Icons like fontawesome) but I also don't want to maintain and we could reserve this method for Icons that aren't available with Heroicon

I've been using https://www.svgrepo.com/ if ever I need to find the right Icons.

**Review by rjvillanueva89 — COMMENTED** [review]
I agree with @pgdureza; let's not manage the base Icons

**Review by rjvillanueva89 — APPROVED** [review]

**Pull request merged**
